server:
  port: 9527

baidu:
  face:
    app-name: property_face
    #app-id:  25798253
    #app-key: 8FH4xcAgXOyeTbC0kUUtCipE
    #secret-key: CK9FcAOXyl3SoAASg2yeXANSekTDVnUu
    app-id: 30471959
    app-key: oPKnV9rar9mxHz2UyE7KMXGi
    secret-key: 5PVs02BXp0drhljmeyBZGjiI2mImhLYe


spring:
  main:
    allow-circular-references: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

  datasource:
    dynamic:
      # 是否开启 SQL日志输出，生产环境建议关闭，有性能损耗
      p6spy: false
      hikari:
        connection-timeout: 30000
        max-lifetime: 1800000
        max-pool-size: 15
        min-idle: 5
        connection-test-query: select 1
        pool-name: FebsHikariCP
      # 配置默认数据源
      primary: primary
      datasource:
        # 数据源-1，名称为 primary
        primary:
          username: root
          password: DzKmzDatzZFNBFEP
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://1.14.170.236:13306/property_cos?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai

  aop:
    proxy-target-class: true

  messages:
    encoding: utf-8

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  redis:
    host: 1.14.170.236
    port: 26739
    password: p7GxPL5PsMFXtP6T
    jedis:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 0


#mybatis plus 设置
mybatis-plus:
  type-aliases-package: cc.mrbird.febs.system.domain,cc.mrbird.febs.job.domain
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
    jdbc-type-for-null: null
    call-setters-on-nulls: true
  global-config:
    # 关闭 mybatis-plus的 banner
    banner: false

management:
  endpoints:
    web:
      exposure:
        include: ['httptrace', 'metrics']


  quartz:
    job-store-type: jdbc
    properties:
      org:
        quartz:
          scheduler:
            instanceName: MyScheduler
            instanceId: AUTO
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 20
            threadPriority: 5
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            clusterCheckinInterval: 15000
            maxMisfiresToHandleAtATime: 1
            misfireThreshold: 12000
            useProperties: false

febs:
  # 是否异步记录用户操作日志
  openAopLog: true
  # 单次最大批量入库数量
  max:
    batch:
      insert:
        num: 1000
  shiro:
    # 后端免认证接口 url
    anonUrl: /login,/logout/**,/regist,/user/check/**,/file/**,/imagesWeb/**,/cos/payment-manage/ali/**,/cos/face/**
    # token有效期，单位秒
    jwtTimeOut: 3600

minio:
  endpoint: http://1.14.170.236:19000
  access-key: bERJuw9csaSUsTgHRA1D
  secret-key: BYP5IQC9K4soCD4BUPFtozdb0M7zfbSB22r8w3if
  bucket-name: property-cos